### ISSUE TITLE
Cannot find name 'KnockoutObservable'. in survey.angular.d.ts

### ISSUE THREAD

**Issue by shahrin014** [surveyjs/surveyjs_angular_cli#14]
I am using this in my ionic3 project.
I installed the necessary packages
```sh
npm install --save survey-angular
npm install --save @types/knockout
npm install --save @types/json5
```

And I updated the typings in my tsconfig.app.json file

However when I build my application, I still find the following error.
```
[10:31:50]  typescript: .../ionic/app/node_modules/survey-angular/survey.angular.d.ts, line: 640
            Cannot find name 'KnockoutObservable'.

     L639:      constructor(question: Question);
     L640:      protected updateValue(newValue: any): void;

[10:31:50]  typescript: .../ionic/app/node_modules/survey-angular/survey.angular.d.ts, line: 641
            Cannot find name 'KnockoutComputed'.

     L640:      protected updateValue(newValue: any): void;
     L642:  export declare class QuestionFile extends QuestionFileModel {

[10:31:50]  typescript: .../ionic/app/node_modules/survey-angular/survey.angular.d.ts, line: 642
            Cannot find name 'KnockoutComputed'.

     L642:  export declare class QuestionFile extends QuestionFileModel {
     L643:      name: string;

[10:31:50]  typescript: .../ionic/app/node_modules/survey-angular/survey.angular.d.ts, line: 643
            Cannot find name 'KnockoutObservable'.

     L642:  export declare class QuestionFile extends QuestionFileModel {
     L643:      name: string;
     L644:      constructor(name: string);
```

My temporary workaround is to add the following line in survey.angular.d.ts, at line 638
`
import * as ko from 'knockout';
`

But I am hoping for a proper solution.

**Comment by dmitry-kurmanov** [comment]
@shahrin-14 hello! Could you please check an example: https://github.com/abritopach/ionic-surveyjs created by @abritopach ?

**Comment by edwinborda** [comment]
in src/polyfills.ts add 

`import * as ko from 'knockout';
window['knockout'] = ko;`

It worked for me!!

**Comment by dmitry-kurmanov** [comment]
@edwinborda Hello! Thank you for the suggestion. I've cloned the repo, install all packages and everything works. We are not Angular developers, so may be we missed something. Could you please explain why do we need to add the code above to the repo?

**Comment by jonathan-chin** [comment]
I've tried everything, including @edwinborda 's suggestion to edit the polyfills.ts file. Didn't work. I tried cloning and running the repo @dmitrykurmanov link but it failed `npm install`

The only thing that has worked is editing survey.angular.d.ts like @shahrin-14 mentioned.

**Comment by CoderCuts** [comment]
My team is still having this issue, has anyone found a more permanent fix?

**Comment by thxmike** [comment]
I am still having this same issue with an Angular 8 application. I am trying to import the parts into an existing project I have. 
Here are some differences:
I am using a nested module. The app.module to bootstrap the application and a navigation module to load the navigation components
I use routing in the navigation module.

Here is what I did:

npm install -save survey-angular
npm install -save surveyjs-widgets
npm install -save survey-creator
npm install -save survey-knockout # This was added since it is referenced in the package.json

--navigation.module.ts
In my module, I added the following imports:
import { SurveyComponent } from '../components/survey/survey.component';
import { SurveyCreatorComponent } from '../components/survey/survey.creator.component';
import { Survey2Component } from '../components/survey2/survey2.component'; //Consumer of the component

and in the declarations
 SurveyComponent,
 SurveyCreatorComponent,
 Survey2Component

--polyfill.ts
I tried adding:
import * as jQuery from 'jquery';
window['jQuery'] = jQuery;
import * as ko from 'knockout';
window['knockout'] = ko;

-- survey2.component.ts
Added the contents of "app.component.ts"

-- survey2.component.html
Added the contents of app.component.html

-- tsconfig.app.json
"types": ["node", "knockout"]

-- survey.creator.component.ts
updated line:  export class SurveyCreatorComponent implements OnInit  // ngOnInit() is referenced but missing the implements

-- for survey.creator.component.ts and survey.component.ts
Separated the HTML template to a templateUrl

I continually get from multiple files:
error TS2304: Cannot find name 'KnockoutObservable'. 
error TS2304: Cannot find name 'KnockoutComputed'.
error TS2304: Cannot find name 'KnockoutObservableArray'

The files that the errors reference are
./node_modules/survey-creator/survey-creator.d.ts
./node_modules/survey-knockout/survey.ko.d.ts
./node_modules/survey-angular/survey.angular.d.ts

Based on what I see, the types are not being exported correctly from 
node_modules/@types/knockout/index.d.ts

I am not sure how knockout works but it may be a setup issue. 

If a full error is needed it can be provided

**Comment by thxmike** [comment]
After some digging I found this thread
https://github.com/surveyjs/survey-creator/issues/472

It appears there is a problem with version of knockout. I explicitly downgraded the version of knockout with the following command:

npm install knockout@3.4.2 --save

and it prevented any further errors from occurring.

**Comment by wollerman** [comment]
Make sure your tsconfig also has:
```
"compilerOptions": {
        "types": ["knockout"]
    },
```

**Comment by crsepulv** [comment]
I removed the "@types/knockout" and works: [https://surveyjs.answerdesk.io/ticket/details/t3086/cannot-find-namespace-ko](https://surveyjs.answerdesk.io/ticket/details/t3086/cannot-find-namespace-ko)
