### ISSUE TITLE
Custom widget

### ISSUE THREAD

**Issue by npupiec** [surveyjs/surveyjs_angular_cli#32]
Hi 
How can I add custom widget (https://next.plnkr.co/edit/fXsLf1R88WxxDFaFEnYx?p=preview&preview) to SurveyJS Creator??

When I import file customwidget.js to my SurveyJS Creator component nothing happend. Thanks

**Comment by tsv2013** [comment]
As you can see, custom widget is added automatically after registration:
![image](https://user-images.githubusercontent.com/3013415/67187332-a527e080-f3f2-11e9-96a1-56b68c93ee79.png)

But for the angular version you need to register a custom widget in survey-angular
```JS
Survey.CustomWidgetCollection.Instance.addCustomWidget(widget, "customtype");
```
and in the survey-knockout (because survey-creator uses the survey-knockout library):
```JS
SurveyKo.CustomWidgetCollection.Instance.addCustomWidget(widget, "customtype");
```

**Comment by npupiec** [comment]
@tsv2013 thank you
When I do this I get error in console ERROR TypeError: Cannot read property 'getType' of null

**Comment by tsv2013** [comment]
@npupiec  Can you share a sample to reproduce the issue?
